[target.riscv32imc-unknown-none-elf]
rustflags = [
    "-C",
    "link-arg=-Tlinkall.x",
    "-C",
    "link-arg=-Tesp32c3_rom_functions.x",

    "-C",
    "force-frame-pointers",
    # For defmt
    "-C",
    "link-arg=-Tdefmt.x",
]

[build]
# We compile without atomics, because its faster than using atomic trap handler
target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["core", "alloc"]

[env]
# You can override this via environment variable when building or by changing it here
DEFMT_LOG = "trace"

SSID = "ssid"
PASSWORD = "password"
