on:
  push:
    paths:
      - .github/workflows/firmware-ci.yml
      - firmware/**
      - package*.json
  pull_request:
    paths:
      - .github/workflows/firmware-ci.yml
      - firmware/**
  workflow_dispatch:

jobs:
  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd firmware

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

  clippy:
    name: Linting
  
    strategy:
      matrix:
        mcu: [mcu-esp32c3, mcu-esp32, mcu-nrf52840]
        imu: [imu-stubbed, imu-mpu6050]
        net: [net-stubbed, net-wifi]
        log: [log-rtt, log-usb-serial, log-uart]
        include:
          - mcu: mcu-esp32c3
            target: riscv32imc-unknown-none-elf
          - mcu: mcu-esp32
            target: xtensa-esp32-none-elf
          - mcu: mcu-nrf52840
            target: thumbv7em-none-eabihf
        exclude:
          - mcu: mcu-esp32
            log: log-usb-serial
          - mcu: mcu-nrf52840
            net: net-wifi
    env:
      FEATURES: ${{ format('{0},{1},{2},{3}', matrix.mcu, matrix.imu, matrix.net, matrix.log) }}
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - run: cd firmware

      - name: Install Xtensa toolchain
        if: matrix.target == 'xtensa-esp32-none-elf'
        uses: esp-rs/xtensa-toolchain@v1.3
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - run: cargo install clippy-sarif sarif-fmt

      - if: matrix.target == 'xtensa-esp32-none-elf'
        run: rustup override set esp
      - name: Clippy lints
        run: cargo clippy --target ${{ matrix.target }} --no-default-features --features $FEATURES --message-format=json |
          clippy-sarif | tee results.sarif | sarif-fmt
